### ISSUE TITLE
Error in manage.py, Python 3 Compatibility, and re-order sequence in README

### ISSUE THREAD

**Issue by perllaghu** [ccnmtl/django-lti-provider-example#3]
The first line of `manage.py` should read `#!/usr/bin/env python`

update `requirements.txt` to use `django-lti-provider==0.2.2`

This is how I got my test example up & running..... and testable with an external Basic LTI Consumer (which is different to the README):

**Local database**
postgres database stuff:
- create user (eg djlti)
-  set password for user
-  create database (eg django-lti-provider-example)

**Grab the code**
`git clone https://github.com/ccnmtl/django-lti-provider-example.git`
`cd django-lti-provider-example/`

**Setup the example server**
copy `djangoltiproviderexample/local_settings.py.example` to `djangoltiproviderexample/local_settings.py`

edit djangoltiproviderexample/local_settings.py :
    set `NAME`, `HOST`, `USER`, and `PASSWORD`
    remove `PORT` (unless it's non-standard)
    add `ALLOWED_HOSTS = [
    'localhost',
    '.your.blackboard.or.moodle.domain',
    '.your.workstation.domain',
    ]`
    add `PYLTI_CONFIG = { 'consumers': { '<key>': { 'secret': '<secret>' } } }`
    maybe add `LTI_EXTRA_PARAMETERS = ['custom_myparama', 'custom_myparamb']`

By default, you can't access the example from outside the local box. edit `django.mk` and set `INTERFACE ?= 0.0.0.0` rather than `localhost` to get the app to listen to the public network

Setup virtualenv for the code: `virtualenv -p python3 .` and activate `source bin/activate`

Now install the code needed: `pip install -r requirements.txt`

Set up the database: `./manage.py migrate`

Build the app: `make`

Run the app: `make runserver`

Happy days.... 
(and thank you - brilliant bit of code, and saved me *loads* of headache - trying to get my head round all this stuff!!)

**Comment by nikolas** [comment]
Thanks for the feedback. I have a question about your first suggestion, changing the first line of `manage.py` to `#!/usr/bin/env python`. As stated in our README, running `make` should create the virtualenv at `ve/` and allow for python to be available at `./ve/bin/python`. Is this not happening in your case? It should run this make target here: https://github.com/ccnmtl/django-lti-provider-example/blob/master/django.mk#L28
