### ISSUE TITLE
Issues with the make file

### ISSUE THREAD

**Issue by eoktay** [ccnmtl/django-lti-provider-example#78]
Hi there,

Thanks for this useful example! 

Just a quick question, when I tried to run the make file, I got the following error: 

> AttributeError: module 'enum' has no attribute 'IntFlag'
django.mk:43: recipe for target 'flake8' failed
make: *** [flake8] Error 1

Looking through both `django-lti-provider` and `django-lti-provider-example`, I can see that the former was [updated to support the latest version of Django along with some other additions](https://github.com/ccnmtl/django-lti-provider/commit/017f87e798054846691ac1bd0bf7aed77f452822#diff-fdaa2edbb1e3772fb7c998d5324dee25). Looking at the [requirements](https://github.com/ccnmtl/django-lti-provider-example/blob/master/requirements.txt) for `django-lti-provider-example`, I still see an older version of Django: 'Django==1.11.12'. 

I was just curious to know if you were planning on upgrading the code for `django-lti-provider-example` in line with the [changes](https://github.com/ccnmtl/django-lti-provider/commit/017f87e798054846691ac1bd0bf7aed77f452822#diff-fdaa2edbb1e3772fb7c998d5324dee25) made on `django-lti-provider`. 

Thanks very much!

**Comment by sdreher** [comment]
Hi @eoktay - I think the errors you're running into might be python3 compatibility issues. We're in the process of upgrading everything to python3, Django 2.0, likely in the next several weeks. We're happy to accept a pull request as well if you're in a hurry and need changes earlier.
Thanks!
Susan
